version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    tty: true
    stdin_open: true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - "SERVER_NAME=kibana"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - esnet
    tty: true
    stdin_open: true

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.2
    container_name: filebeat
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - fbndata:/usr/share/filebeat/data
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./elastic-template-logtrace.json:/usr/share/filebeat/elastic-template-logtrace.json:ro
      - ..:/app
    command: filebeat -e -strict.perms=false -E output.elasticsearch.hosts=["elasticsearch:9200"] -E setup.kibana.host=kibana:5601
    networks:
      - esnet
    tty: true
    stdin_open: true

  fluentbit:
    image: fluent/fluent-bit:1.3
    container_name: fluentbit
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit-parsers.conf:/fluent-bit/etc/fluent-bit-parsers.conf:ro
      - ..:/app
    ports:
      - 2020:2020
      - 24224:24224
    networks:
      - esnet
    tty: true
    stdin_open: true

  alpine:
    image: alpine:latest
    container_name: alpine
    depends_on:
      - fluentbit
    networks:
      - esnet
    tty: true
    stdin_open: true
    logging:
      driver: fluentd
      options:
#        tag: docker-alp
#        mode: blocking
#        max-buffer-size: 1m
        fluentd-address: host.docker.internal:24224

volumes:
  esdata:
    driver: local
  fbndata:
    driver: local
  fbtdata:
    driver: local

networks:
  esnet:
    driver: bridge
